# Generated by Django 5.1.2 on 2024-11-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_certificate_education_honorandaward_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheCanStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shecan_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
