# Generated by Django 5.1.2 on 2024-11-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_shecanstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shecanstudent',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
