# Generated by Django 5.1.2 on 2024-12-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_photogallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
