# Generated by Django 5.1.2 on 2024-12-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_program_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='projectname',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
