# Generated by Django 5.1.2 on 2024-12-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_project_color_projectname_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shecan',
            name='cohert',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
