# Generated by Django 5.1.2 on 2024-12-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_category_productphoto_product_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
