# Generated by Django 5.1.2 on 2024-12-15 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_product_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.product'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(help_text='e.g., XS, S, M, L, XL or Small, Medium, Large ... ', max_length=20),
        ),
    ]
