# Generated by Django 5.1.2 on 2024-12-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_category_image_alter_productphoto_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='icon',
        ),
    ]
