# Generated by Django 5.1.2 on 2025-01-17 13:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_image_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('grandfathers_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(choices=[('Ethiopian', 'Ethiopian'), ('Ethiopian Diaspora', 'Ethiopian Diaspora'), ('Other', 'Other')], max_length=20)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], max_length=10)),
                ('employment_status', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Not Employed', 'Not Employed'), ('Self Employed', 'Self Employed'), ('Homemaker', 'Homemaker'), ('Retired', 'Retired'), ('Student', 'Student'), ('Other', 'Other')], max_length=20)),
                ('education', models.CharField(choices=[('Less than High School Diploma', 'Less than High School Diploma'), ('High School Diploma', 'High School Diploma'), ('College / University Student', 'College / University Student'), ('Bachelors Degree', 'Bachelors Degree'), ('Msc', 'Msc'), ('PHD', 'PHD')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('second_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True)),
                ('field_of_work', models.CharField(max_length=100)),
                ('work_experience', models.CharField(choices=[('0-1', '0-1'), ('2-5', '2-5'), ('5-8', '5-8'), ('Above 9 years', 'Above 9 years')], max_length=20)),
                ('available_hours', models.CharField(choices=[('0-5 hours', '0-5 hours'), ('5-10 hours', '5-10 hours'), ('11-20 hours', '11-20 hours'), ('21-30 hours', '21-30 hours'), ('31-40 hours', '31-40 hours'), ('More than 40 hours', 'More than 40 hours')], max_length=20)),
                ('interests', models.CharField(choices=[('Architecture', 'Architecture'), ('Art', 'Art'), ('Crafting and DIY', 'Crafting and DIY'), ('Design', 'Design'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Interior Design', 'Interior Design'), ('Gaming', 'Gaming'), ('Leadership', 'Leadership'), ('Literature', 'Literature'), ('Music', 'Music'), ('Photography', 'Photography'), ('Science', 'Science'), ('Sport', 'Sport'), ('Technology', 'Technology'), ('Woman Empowerment', 'Woman Empowerment'), ('Youth Empowerment', 'Youth Empowerment')], max_length=50)),
                ('preferred_team', models.CharField(choices=[('Creative and Art', 'Team Creative and Art'), ('Engineering', 'Team Engineering'), ('Event & Fund Raising', 'Team Event & Fund Raising'), ('Research and Development', 'Team Research and Development'), ('Technology', 'Team Technology'), ('Training & Consult', 'Team Training & Consult'), ('Legal', 'Team Legal')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
